"""Render DailyBriefing to Markdown and JSON output files."""

from __future__ import annotations
import logging
from pathlib import Path

from jinja2 import Environment, BaseLoader

from threats.models import DailyBriefing

log = logging.getLogger(__name__)

_MD_TEMPLATE = """\
# Daily Threat Intelligence Briefing
## {{ briefing.briefing_date }} | Generated {{ briefing.generated_at.strftime('%Y-%m-%d %H:%M UTC') }}{% if briefing.since_label %} | Since {{ briefing.since_label }}{% endif %}

---
{% if briefing.llm_warning %}

> **⚠ LLM Unavailable:** {{ briefing.llm_warning }}
> IOC and TTP extraction is regex-only this run. Severity scores, summaries, actor attribution, and Sigma FP review are not available.

---
{% endif %}
{% if briefing.is_empty %}

## No New Threat Data

No new threat intelligence has been collected since the last run{% if briefing.since_label %} ({{ briefing.since_label }}){% endif %}.
The pipeline is operating normally and will report when new indicators or reports are available.

---
*Generated by Daily Threat Intel | MITRE ATT&CK® is a trademark of The MITRE Corporation*
{% else %}

## Executive Summary

{{ briefing.executive_summary or "No new findings to highlight today." }}

---
{% if briefing.multi_source_clusters %}

## Multi-Source Incidents ({{ briefing.multi_source_clusters | length }})

*The following incidents were reported independently by multiple research teams, indicating higher confidence.*

{% for cluster in briefing.multi_source_clusters | sort(attribute='severity', reverse=True) %}
### {{ cluster.name }}

- **Sources** ({{ cluster.source_count }}): {{ cluster.sources | join(' · ') }}
- **Severity**: {{ "%.0f" | format(cluster.severity * 100) }}%
- **Active**: {{ cluster.first_seen.strftime('%Y-%m-%d') }} → {{ cluster.last_seen.strftime('%Y-%m-%d') }}
{% if cluster.ttps %}
- **TTPs**: {{ cluster.ttps | map(attribute='technique_id') | join(', ') }}
{% endif %}
{% if cluster.iocs %}

**Consolidated IOCs** ({{ cluster.iocs | length }} total):
{% for ioc in cluster.iocs[:15] %}
{% if ioc.likely_fp %}
- ~~`{{ ioc.type.value }}`: `{{ ioc.value }}`~~ ⚠️ *likely false positive*
{% else %}
- `{{ ioc.type.value }}`: `{{ ioc.value }}` · fidelity: **{{ ioc.fidelity }}** · sources: {{ ioc.source_count }}{% if ioc.specificity_note %} · *{{ ioc.specificity_note }}*{% endif %}{% if ioc.tags %} · {% for t in ioc.tags %}`{{ t }}`{% if not loop.last %} {% endif %}{% endfor %}{% endif %}
{% endif %}
{% endfor %}
{% if cluster.iocs | length > 15 %}
- *({{ cluster.iocs | length - 15 }} more in JSON output)*
{% endif %}
{% endif %}

---
{% endfor %}
{% endif %}

## Threat Landscape Statistics

| Metric | Count |
|--------|-------|
| Multi-Source Incidents | {{ briefing.multi_source_clusters | length }} |
| Total Clusters | {{ briefing.clusters | length }} |
| New Intel Items (this period) | {{ briefing.items | length }} |
| Critical Items | {{ briefing.critical_items | length }} |
| High Items | {{ briefing.high_items | length }} |
| New Threat Actors | {{ briefing.new_actors | length }} |
| Returning Actors | {{ briefing.returning_actors | length }} |
| **New IOCs** | **{{ briefing.ioc_counts.new }}** |
| Re-observed IOCs | {{ briefing.ioc_counts.reobserved }} |
| New TTPs | {{ briefing.new_ttps | length }} |
| Re-observed TTPs | {{ briefing.reobserved_ttps | length }} |
| Sigma Rules Generated (new only) | {{ briefing.sigma_rules | length }} |

### IOC Breakdown (new + re-observed)
{% for ioc_type, count in briefing.ioc_counts.by_type.items() %}
- **{{ ioc_type }}**: {{ count }}
{% endfor %}

---
{% if briefing.new_actors %}

## New Threat Actors (First Observed This Period)
{% for actor in briefing.new_actors %}

### {{ actor.name }}
- **Aliases**: {{ actor.aliases | join(', ') or 'None documented' }}
- **Motivation**: {{ actor.motivation or 'Unknown' }}
- **Origin**: {{ actor.origin or 'Unknown' }}
- **Targeted Sectors**: {{ actor.targeted_sectors | join(', ') or 'Unknown' }}
- **Targeted Regions**: {{ actor.targeted_regions | join(', ') or 'Unknown' }}
- **Attribution Confidence**: {{ "%.0f" | format(actor.confidence * 100) }}%
{% endfor %}
{% endif %}
{% if briefing.returning_actors %}

## Returning Threat Actors (Active This Period)
{% for actor in briefing.returning_actors %}
- **{{ actor.name }}** ({{ actor.motivation or 'unknown motivation' }}) — last seen {{ actor.last_seen.strftime('%Y-%m-%d') }}
{% endfor %}
{% endif %}

---

## Intelligence Items
{% for severity_label, items in [('CRITICAL', briefing.critical_items), ('HIGH', briefing.high_items)] %}
{% if items %}

### {{ severity_label }} Severity
{% for item in items %}

#### {{ item.title }}
- **Source**: [{{ item.source_name }}]({{ item.source_url }})
- **Published**: {{ item.published_at.strftime('%Y-%m-%d') if item.published_at else 'Unknown' }}
- **Severity**: {{ item.severity_label }} ({{ "%.0f" | format(item.severity * 100) }}%)
{% if item.actors %}
- **Actors**: {{ item.actors | map(attribute='name') | join(', ') }}
{% endif %}
{% if item.targeted_sectors %}
- **Targeted Sectors**: {{ item.targeted_sectors | join(', ') }}
{% endif %}
{% if item.summary %}

> {{ item.summary }}
{% endif %}
{% if item.iocs %}

**IOCs** ({{ item.iocs | length }} total):
{% for ioc in item.iocs[:10] %}
{% if ioc.likely_fp %}
- ~~`{{ ioc.type.value }}`: `{{ ioc.value }}`~~ ⚠️ *likely false positive*
{% else %}
- `{{ ioc.type.value }}`: `{{ ioc.value }}` · fidelity: **{{ ioc.fidelity }}** · sources: {{ ioc.source_count }}{% if ioc.specificity_note %} · *{{ ioc.specificity_note }}*{% endif %}{% if ioc.tags %} · {% for t in ioc.tags %}`{{ t }}`{% if not loop.last %} {% endif %}{% endfor %}{% endif %}
{% endif %}
{% endfor %}
{% if item.iocs | length > 10 %}
- *({{ item.iocs | length - 10 }} more — see JSON output)*
{% endif %}
{% endif %}
{% if item.ttps %}

**TTPs**: {{ item.ttps | map(attribute='technique_id') | join(', ') }}
{% endif %}

---
{% endfor %}
{% endif %}
{% endfor %}

## All Items (by source)
{% for item in briefing.items | sort(attribute='source_name') %}
- [{{ item.severity_label }}] **{{ item.title }}** — {{ item.source_name }} — {{ item.published_at.strftime('%Y-%m-%d') if item.published_at else 'n/d' }}
  {{ item.source_url }}
{% endfor %}

---
{% if briefing.new_ttps %}

## New TTPs (First Observed This Period)

| Technique ID | Name | Tactic |
|---|---|---|
{% for ttp in briefing.new_ttps %}
| `{{ ttp.technique_id }}` | {{ ttp.name or "—" }} | {{ ttp.tactic.value if ttp.tactic else "—" }} |
{% endfor %}
{% endif %}
{% if briefing.reobserved_ttps %}

## Re-observed TTPs (Active Again This Period)

| Technique ID | Name | Tactic |
|---|---|---|
{% for ttp in briefing.reobserved_ttps %}
| `{{ ttp.technique_id }}` | {{ ttp.name or "—" }} | {{ ttp.tactic.value if ttp.tactic else "—" }} |
{% endfor %}
{% endif %}

---
{% if briefing.new_iocs %}

## New IOCs (First Seen This Period) — {{ briefing.new_iocs | length }} total

{% for ioc_type in ["IP", "DOMAIN", "SHA256", "SHA1", "MD5", "URL"] %}
{% set typed = briefing.new_iocs | selectattr("type.value", "equalto", ioc_type) | list %}
{% if typed %}
### {{ ioc_type }} ({{ typed | length }})
{% for ioc in typed[:50] %}
{% if ioc.likely_fp %}
- ~~`{{ ioc.value }}`~~ ⚠️ *likely false positive*
{% elif ioc.context_dependent %}
- `{{ ioc.value }}` · fidelity: **low** · sources: {{ ioc.source_count }} · ⚡ *context-dependent — correlate with other indicators*
{% else %}
- `{{ ioc.value }}` · fidelity: **{{ ioc.fidelity }}** · sources: {{ ioc.source_count }}{% if ioc.specificity_note %} · *{{ ioc.specificity_note }}*{% endif %}{% if ioc.tags %} · {% for t in ioc.tags %}`{{ t }}`{% if not loop.last %} {% endif %}{% endfor %}{% endif %}

{% endif %}
{% endfor %}
{% if typed | length > 50 %}
- *({{ typed | length - 50 }} more in JSON output)*
{% endif %}

{% endif %}
{% endfor %}
{% endif %}
{% if briefing.reobserved_iocs %}

## Re-observed IOCs (Previously Documented, Active Again) — {{ briefing.reobserved_iocs | length }} total

{% for ioc_type in ["IP", "DOMAIN", "SHA256", "SHA1", "MD5", "URL"] %}
{% set typed = briefing.reobserved_iocs | selectattr("type.value", "equalto", ioc_type) | list %}
{% if typed %}
### {{ ioc_type }} ({{ typed | length }})
{% for ioc in typed[:20] %}
{% if ioc.likely_fp %}
- ~~`{{ ioc.value }}`~~ ⚠️ *likely false positive — first seen {{ ioc.first_seen.strftime("%Y-%m-%d") }}*
{% elif ioc.context_dependent %}
- `{{ ioc.value }}` · fidelity: **low** · sources: {{ ioc.source_count }} · ⚡ *context-dependent · first seen {{ ioc.first_seen.strftime("%Y-%m-%d") }}*
{% else %}
- `{{ ioc.value }}` · fidelity: **{{ ioc.fidelity }}** · sources: {{ ioc.source_count }}{% if ioc.specificity_note %} · *{{ ioc.specificity_note }}*{% endif %}{% if ioc.tags %} · {% for t in ioc.tags %}`{{ t }}`{% if not loop.last %} {% endif %}{% endfor %}{% endif %} · first seen {{ ioc.first_seen.strftime("%Y-%m-%d") }}
{% endif %}
{% endfor %}
{% if typed | length > 20 %}
- *({{ typed | length - 20 }} more in JSON output)*
{% endif %}

{% endif %}
{% endfor %}
{% endif %}

---
*Generated by Daily Threat Intel | MITRE ATT&CK® is a trademark of The MITRE Corporation*
{% endif %}
"""


def render_briefing(briefing: DailyBriefing, output_dir: Path, formats: list[str] | None = None) -> dict[str, Path]:
    """Render the briefing to configured formats. Returns dict of format→path."""
    if formats is None:
        formats = ["md", "json"]
    output_dir.mkdir(parents=True, exist_ok=True)
    date_str = briefing.briefing_date.isoformat()
    written: dict[str, Path] = {}

    if "md" in formats:
        env = Environment(loader=BaseLoader(), trim_blocks=True, lstrip_blocks=True)
        tmpl = env.from_string(_MD_TEMPLATE)
        md_content = tmpl.render(briefing=briefing)
        md_path = output_dir / f"{date_str}.md"
        md_path.write_text(md_content, encoding="utf-8")
        written["md"] = md_path
        log.info("Wrote Markdown briefing: %s", md_path)

    if "json" in formats:
        json_path = output_dir / f"{date_str}.json"
        json_path.write_text(briefing.model_dump_json(indent=2), encoding="utf-8")
        written["json"] = json_path
        log.info("Wrote JSON briefing: %s", json_path)

    return written
